# This is a basic workflow to help you get started with Actions

name: TEST2 CI/CD PIPELINE

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: golang

    steps:
      - uses: actions/checkout@v2
      - name: Install & Tests
        run: |
          cd Test 2
          go install
          go test
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t builtImage ./Test 2/Dockerfile
      - name: Tags
        run: |
          docker tag builtImage ${{ secrets.DOCKER_USER }}/test2:${{ github.sha }}
          docker tag builtImage ${{ secrets.DOCKER_USER }}/test2:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/test2:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/test2:latest
