# This is a basic workflow to help you get started with Actions

name: TEST2 CI/CD PIPELINE

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: golang

    steps:
      - uses: actions/checkout@v2
      - name: Install & Tests
        run: |
          cd "Test 2"
          go test
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.1.jh5
        with:
          github_token: ${{ secrets.TAG_TOKEN }}
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/test2:${{ github.sha }} -t ${{ secrets.DOCKER_USER }}/test2:latest ./Test 2/Dockerfile --build-arg VERSION=${{ needs.ci.outputs.new_version }} --build-arg COMMITSHA=${{ github.sha }}
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/test2:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/test2:latest
