# This is a basic workflow to help you get started with Actions

name: TEST2 CI/CD PIPELINE

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: golang

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          cd "Test 2"
          go test -v -cover

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.28
          working-directory: "Test 2"


      - name: Run Gosec Security Scanner
        uses: ynniss/golang-security-action@master
        with:
          CODE_PATH: "./Test 2/"

  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag
        uses: hennejg/github-tag-action@v4.1.jh5
        with:
          github_token: ${{ secrets.TAG_TOKEN }}

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/test2:${{ github.sha }} -t ${{ secrets.DOCKER_USER }}/test2:latest --build-arg VERSION=${{ steps.tag.outputs.new_version }} --build-arg COMMITSHA=${{ github.sha }} "Test 2/"

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/test2:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/test2:latest
